biolab/orange-widget-base

- orangewidget/settings.py
- orangewidget/workflow/config.py
- orangewidget/workflow/mainwindow.py
Ref https://github.com/biolab/orange3/pull/3932#discussion_r302905952
Make the `settings.widget_settings_dir` the preferred source with an explicit setter/override.
Deprecate other accessors aliases.
> Deprecate config.widget_settings_dir

- orangewidget/report/report.py
Ref https://github.com/biolab/orange3/issues/3661
`report_plot` raises an error when WebviewWidget is not available.
Guard against a missing WebviewWidget.
> [FIX] report: Fix an import error when WebView is not available

- orangewidget/io.py
- orangewidget/utils/PDFExporter.py
If LosslessImageRendering is not set, the colors in exported files are off: biolab/orange3#3872
Set LosslessImageRendering render hint.
> PDF export with lossless image rendering for Qt>=5.13

- orangewidget/utils/saveplot.py
- orangewidget/utils/tests/test_save_plot.py
It is not possible to pass default file name to Save graph dialog. 
Enable passing default file name to the dialog.
> save_plot: Pass default file name to Save file dialog

- orangewidget/gui.py
https://github.com/biolab/orange3/issues/3910
Added `auto_send` and `auto_apply` convenience functions wrapping `auto_commit`, to expose a more appropriate interface to programmers, encouraging a consolidation in widget interface style, while making a distinction between widgets that apply changes and widgets that send selected data.
> gui: Add auto_send and auto_apply convenience functions

- orangewidget/workflow/errorreporting.py
Currently, if `machine-id` is set to empty string, it [defaults to the system's mac address](https://docs.python.org/2/library/uuid.html#uuid.getnode).
The user should be able to set their machine ID to an empty string.
To be merged after https://github.com/biolab/orange3/pull/3999.
> errorreporting: Remove mac address as default machine ID

- orangewidget/gui.py
https://github.com/biolab/orange3/issues/3910
Amend auto_commit docstring, encouraging developers to use `auto_apply` or `auto_send` instead.
> Amend auto_commit docstring

- orangewidget/workflow/errorreporting.py
Should the machine ID not be initialized, generate it upon sending a report.
> errorreporting: Initialize machine ID upon sending report

- orangewidget/tests/base.py
- orangewidget/utils/signals.py
The following code doesn't send a signal to widget `w` but to `self.widget` although signals are specified as `w.Inputs.data` and `w.Outputs.selected_data`:
``` 
w = self.create_widget(OWSomeWidget)
self.send_signal(w.Inputs.data, data)
out = self.get_output(w.Outputs.selected_data)
```
To make it work, the widget has to be given explicitly:
``` 
w = self.create_widget(OWSomeWidget)
self.send_signal(w.Inputs.data, data, widget=w)
out = self.get_output(w.Outputs.selected_data, widget=w)
```
This bites me every time I manually construct a widget in a test, for instance to test settings.
Outputs are already bound to widgets, so we simply use `w.Outputs.selected_data.widget` as default.
Inputs are not yet bound, but it's a simple change and although this is needed only for tests, it's not a …
> Use bound signals in `WidgetTest.send_signal` and `get_output`

- orangewidget/gui.py
Uses ForegroundRole for the indicator color.
This will be used by Data sets widget to indicate the currently output data set (see
https://github.com/biolab/orange3/pull/4071).
> gui.IndicatorItemDelegate: Allow setting indicator color

- orangewidget/workflow/errorreporting.py
In certain cases, the UUID python object was written to config as `machine_id` instead of a string. This change casts it to string before writing it to config.
> Fix incorrectly set machine id

- orangewidget/widget.py
https://github.com/biolab/orange3/pull/4056
https://github.com/biolab/orange-canvas-core/pull/31
In an effort to avoid eliding text in the toolbox, a `short_name` property was added to widgets and `WidgetDescription`, which overrides the text in the toolbox.
> Short names for widgets whose name elides in toolbox

- orangewidget/gui.py
1. Argument `valueType` can be guessed from attribute value. If they mismatch, it is an error anyway.
`lineEdit` keeps the argument, but guesses by default.
For `comboBox`, the argument is removed (with a warning if still given). There, argument `valueType` was also incompatible with giving argument `model`.
2. `comboBox` did not set the proper callbacks/callfronts for models. For this reason, the function was reimplemented in orange3 code. I suppose this is because uses `VariableListModel`. I believe this is unnecessary: `PyListModel`, which is present in orange-widget-base suffices. This PR adds the model-related callbacks here and removes `comboBox` reimplementation from orange3 repository.
> Simplify gui.lineEdit and gui.comboBox

- orangewidget/settings.py
- orangewidget/tests/test_context_handler.py
Fixes https://github.com/biolab/orange3/issues/4185.
As @ales-erjavec explained, Orange always asks whether to save the schema (at least) if if contains widgets with context settings. This happens because context settings are never equal.
This PR provides `Contexts.__eq__` (and, for consistency, also `Context.__hash__`) that ignore time stamps. This should solve a general problem, but individual widgets may still have hidden modified values.
> Context: Add __eq__ and __hash__

- orangewidget/gui.py
Function comboBox stores the label (a string) instead of the corresponding `QLabel`.
> gui.comboBox: Fix stored label

- doc/source/tutorial-utilities.rst
- doc/source/widget.rst
- orangewidget/tests/test_widget.py
- orangewidget/widget.py
Displaying large numbers in i/o summary takes a lot of space.
Shorten large numbers using metric suffixes.
> [ENH] StateInfo: add auto format for numbers

- orangewidget/gui.py
- orangewidget/tests/test_gui.py
Closes #24.
Freshly needed in https://github.com/biolab/orange-widget-base/issues/24, but also applicable in probably any widget that disables check boxes.
In understand that this perpetuates the infamous `gui` module. But *if you're going through hell, keep going* (saith Churchill), and (1) `gui` is not that evil and (2) to have this functionality, someone would have to store the hidden and true states anyway, so it's more practical to have a QCheckBox variant with specific state when disabled.
For testing, try adding argument `stateWhenDisabled=False` to check box for `show_probs` in `OWDistributions` (see patch). Check the check box "Show probabilities"; set "Split by" to "None" (check box will be disabled and also cleared); set "Split by" back to some variable (check box will be …
> gui.checkBox: Show specific state when disabled

- orangewidget/workflow/errorreporting.py
In a land far away, when a user unchecked the 'Send workflow' button in the error reporting dialogue, the .ows's filename was sent instead. About two years ago, a commit removed the filename from the report just before it was sent, in a way that threw an exception if the workflow was empty.
This likely led to some orangecanvas exceptions not being sent.
Not quite sure how `mkstemp` works, so I left the logic there as is.
> Error Reporting: Fix sending report with empty ows

- .travis.yml
- appveyor.yml
- orangewidget/tests/base.py
Running tests with Qt 5.14 prints warning on exit:
```
Release of profile requested but WebEnginePage still not deleted. Expect troubles !
```
See also https://github.com/biolab/orange3/pull/4284
* Remove references from global `WidgetTest.widget` list.
* Add PyQt5 5.14 to test matrix
> [FIX] Tests cleanup

- orangewidget/gui.py
`widget_label` was sometimes unassigned before use.
This didn't bite us because Orange uses a separate definition of `comboBox` (and will until https://github.com/biolab/orange3/pull/4158), but would bite anybody who used orange-widget-base separately.
> gui.comboBox: Fix unassigned local variable

- orangewidget/tests/test_widget.py
- orangewidget/widget.py
When setting input/output summary with an integer value, allow setting the details as well.
- remove single arg check
- use summary as default detail
> [ENH] StateInfo: Allow details along with int summary

- orangewidget/io.py
Exporting a QPicture to SVG can result in wring scale of the exported picture.
This happens when the default screen DPI does not match that of the paint device ([QTBUG-20361](https://bugreports.qt.io/browse/QTBUG-20361))
Examples where this happens: 'Hierarchical clustering', 'Silhouette plot' in Orange3 on Windows, Linux systems were default DPI is 96 (so probably most systems).
* Set svg generator's resolution to match the default screen DPI
> [FIX] io: Set svg generator's resolution to match the default screen

- orangewidget/utils/messagewidget.py
- orangewidget/widget.py
(edited 11th Feb)
- Played around with content margins
- Elide warning/error message
- Fix in/out message size
- Remove in/out message size grip
- In/out messages always have a popup
- Remove first line from popup/tooltip
Before:
After:
> [ENH] Refactor statusbar, prettify

- orangewidget/io.py
QSvgGenerator emits width and height in mm units, while the exported
geometry is unitless. 'viewBox' is emitted unitless and matches the
geometry.
Use `QSvgGenerator.viewBox` instead of `QSvgGenerator.size` to set exported svg viewport
> [FIX] SvgFormat: Set 'viewBox' instead of 'size' to initiate the svg viewport

- orangewidget/tests/base.py
When calling, say `self.get_output(OWContinuize.Outputs.data)` (as opposed to the more usual `self.get_output(self.widget.Outputs.data)`), the widget was retrieved through `getattr(output, "widget", self.widget)`. This however didn't work because `OWContinuize.Outputs.data` is an unbound signal, and unbound signals *do have* an attribute `widget`, but it's set to `None`. 
`getattr(obj, attr) or default` is equivalent to `getattr(obj, attr, default)`, except when ``getattr(obj, attr)` is `None` (it cannot be false in another way here) - which is what we need.
> WidgetTest.get_output: Fix for unbound signals

- orangewidget/settings.py
Second part of the fix for https://github.com/biolab/orange3/issues/4415.
Context handlers currently push only perfect matches to the top. This PR changes the code to push any matching context, even if imperfect.
> Context handlers: Push imperfect matches to the top

- orangewidget/widget.py
When setting input/output summary allow summary to be interpreted as Qt.RichText if summary is an integer.
> StateInfo: Allow int summary to be interpreted as Qt.RichText

- orangewidget/io.py
Fixes #45.
Browsers (and Inkscape) blur svg files. The solution is to insert `style="image-rendering:optimizeSpeed;image-rendering:pixelated"`, but this is apparently impossible because SVG headers in Qt are hard-coded: https://github.com/qt/qtsvg/blob/4cdd71fd2070e439ef7daa8f932f19f76020a45b/src/svg/qsvggenerator.cpp#L896.
Would I lose all respect I might perhaps enjoy if I proposed this patch?
> SVGFormat: Insert 'nonpixelated' into svg style

- orangewidget/tests/base.py
> [FIX] WidgetTest: Handle string parameter when invoking get_output()

- orangewidget/gui.py
- orangewidget/utils/combobox.py
- orangewidget/utils/tests/test_combobox.py
ComboBoxSearch implemented but not included in comboBox fuction.
ComboBoxSearch does not implement maximumContentsLenght, which is implemented in ComboBox.
- Adding a searchable attribute to comboBox function - when True ComboBoxSearch used instead of ComboBox
- Deprecating maximumContentsLenght for ComboBox - reason not really used in practice 
- Setting maximumContentsLenght to the default value of 25.
- Implementing the same behavior for ComboBoxSearch (default max width 25).
> Added search option to comboBox

- orangewidget/utils/tests/test_combobox.py
Version when `maximumContentsLength` need to be removed is to low
It so it is moved to the next version.
> Change version when maximumContentsLength removed to higher

- orangewidget/utils/itemmodels.py
- orangewidget/utils/tests/test_itemmodels.py
See https://github.com/biolab/orange3/pull/4631. Same here.
> PyTableModel: Fix wrapping empty lists in constructor

- orangewidget/utils/filedialogs.py
- orangewidget/utils/tests/test_filedialogs.py
https://github.com/biolab/orange3/issues/4537: `getOpenFileName` sometimes returns an empty filter. We can't reproduce the problem, so this is a blind fix, with a test.
> [FIX] open_filename_dialog: Fix empty filter returned from QFileDialog.getOpenFileName

- orangewidget/settings.py
Any context handler that implements `open_context` with additional arguments (as probably all do!) currently has to redefine `settings_to_widget` solely to pass them do `decode_settings`. E.g. https://github.com/biolab/orange3/blob/master/Orange/widgets/settings.py#L143 differs from the inherited method just by the additional argument `domain`, which is passed to `decode_settings`.
This can be easily avoided by passing the existing `*args` to `decode_settings`. 
`ContextHandler.decode_setting` now accepts `*args` that will swallow any additional arguments, which `settings_to_widget` will now pass and which may not be expected by existing code.
`decode_setting` is currently redefined only in `DomainContextHandler` (which also redefines `settings_to_widget` accordingly), and in select rows, …
> ContextHandler.settings_to_widgets: pass *args to decode_setting

- orangewidget/utils/messagewidget.py
Ref: https://github.com/biolab/orange3/pull/4692#issuecomment-618867450, https://github.com/biolab/orange3/issues/4553#issuecomment-602530513, ..
Give QPropertyAnimation a parent so it is deleted at the same time as the widget.
> [FIX] messagewidget: Give QPropertyAnimation a parent

- orangewidget/utils/combobox.py
- orangewidget/utils/tests/test_combobox.py
ComboBoxSearch(enabled=False) raised an:
```
File "../orangewidget/utils/combobox.py", line 302, in hidePopup
if self.__popup is not None:
AttributeError: 'ComboBoxSearch' object has no attribute '_ComboBoxSearch__popup'
```
Due to virtual override calls from within base QComboBox constructor
Reorder construction sequence
> [FIX] ComboBoxSearch: Fix an AttributeError in hidePopup

- .travis.yml
- orangewidget/utils/concurrent.py
- orangewidget/utils/itemmodels.py
- orangewidget/utils/tests/test_concurrent.py
Ref: https://github.com/biolab/orange3/issues/4553
Implement a workaround for https://www.riverbankcomputing.com/pipermail/pyqt/2020-April/042734.html
> [FIX] concurrent: Implement a workaround for QObject wrapper deletion

- orangewidget/tests/base.py
Same as https://github.com/biolab/orange3/issues/2596 but for tests
Minimum reproducer:
```python
from PyQt5.QtWidgets import QApplication, QGraphicsScene
import pyqtgraph
app = QApplication([])
scene = QGraphicsScene()
group = scene.createItemGroup([])
scene.clear()
```
Disable pyqtgraph exit cleanup handler
> tests: Disable pyqtgraph exit cleanup handler

- orangewidget/utils/filedialogs.py
- orangewidget/utils/tests/test_filedialogs.py
Aims to do the same thing as #53 but with smaller changes to behaviour.
Keeps 
#53 broke:
- Tests in OWFile, which expected None if there was no filter selected. This was already fixed in master, but I think that what the OWFile test expected was fine. Perhaps it would sometimes be useful to know that the user did not choose any specific format
- OWMultifile, because it assumed that all dialogs are going to return strings. Well, some return lists of strings.
- Possibly changed which readers open files, because priorities, which are important when a certain extension can be opened by multiple readers, were handled differently.
#53 added unneeded complexity into a single function, while also semi-duplicating existing functionality.
> open_filename_dialog: fix for returned empty filter

- orangewidget/utils/messagewidget.py
Fixes #63.
Message box was only clickable if more than one message was shown, otherwise whole message was visible only in a tooltip. Now is set to be clickable whenever there is a message.
> MessageWidget: enable messages to be clickable

- orangewidget/gui.py
- orangewidget/utils/combobox.py
- orangewidget/utils/tests/test_combobox.py
The maximum content length was deprecated few versions ago
With this PR it is removed
> Remove deprecated maximumContentLength from combobox

- orangewidget/utils/tests/test_visual_settings_dlg.py
- orangewidget/utils/visual_settings_dlg.py
- orangewidget/widget.py
User is forced to use the predefined dialog when clicking upon the Visual Settings icon in the status bar.
- Enable using custom Visual settings dialog
- Enable using saved settings
- Remove OrderedDict
> [ENH] Visual settings: saving settings, custom dialogs

- orangewidget/tests/base.py
- setup.py
Orange3 macOS tests sometimes stall. One possible reason is macOS App Nap (https://codereview.qt-project.org/c/qt/qtbase/+/202515)
Disable App Nap when running GUI tests
> tests/base: Disable macOS app nap in tests

- orangewidget/utils/visual_settings_dlg.py
Button OK is misleading; it doesn't confirm the changes (as opposed to Cancel), it just closes the window. Perhaps rename to Close, or you can eliminate it.
Rename the button to Close.
> VisualSettingsDialog: Rename OK button to Close

- orangewidget/utils/tests/test_visual_settings_dlg.py
- orangewidget/utils/visual_settings_dlg.py
The Visual Settings dialog should support text editing (e.g. axis title).
- add support for LineEdit control to enable text editing.
- add tooltips
- refactor
> VisualSettingsDialog: Add support for LineEdit, add tooltips

- orangewidget/settings.py
Before the settings were saved with the highest protocol, which made default widget settings saved on Python 3.8 incompatible with older Pythons. It throws up errors when switching Python version.
This removes all (dangerous) HIGHEST_PROTOCOL pickling settings from the orange-widget-base.
Similar to biolab/orange3#4388, but much less of a problem for most users.
> default-settings: save with pickle protocol 4

- orangewidget/gui.py
Some elements (push buttons, comboboxes, checkboxes) have an additional margin at the start of their layout, if they're in a nested layout. That way, these two checkboxes aren't vertically aligned (2px off):
This is what's happening under the hood:
By setting the `WA_LayoutUsesWidgetRect` attribute on all created buttons, comboboxes and checkboxes, you get this:
Without overwriting the stylesheet:
This leads to taller control boxes. In this specific screenshot, it's 6px taller.
It seems to apply to `QPushButton`s, `QComboBox`es, `QCheckBox`es and possibly other items.
https://stackoverflow.com/questions/41452512/how-to-remove-margins-of-qlayout-completely-mac-os-specific
There was a bug reported to QT, but it looks like nothing was done of it due to the existence of a workaround. …
> gui: Align controls (QTBUG-2699 workaround)

- orangewidget/io.py
Tests frequently segfault at process exit e.g. https://travis-ci.org/github/biolab/orange-widget-base/jobs/709922527#L673
One reason for this is  that matplotlib export test creates a qt window which might be destroyed after the QApplication
Force matplotlib backend to pdf for the export
> [FIX] io: Force matplotlib backend to pdf for the export

- orangewidget/tests/utils.py
This is now the prevalent warning in tests. As written by @ales-erjavec in https://github.com/biolab/orange3/pull/4961, it can be removed.
> Remove warning that excepthook has already been overridden

- orangewidget/gui.py
Messages like `Unable to set '<orangewidget.utils.combobox.ComboBoxSearch object at 0x7f133c789ee8>' to 0; largest index is -1` should be warnings for easier debugging and potential silencing.
> CallFrontComboBox: change logs into warnings

- orangewidget/report/index.html
- orangewidget/report/owreport.py
- orangewidget/tests/base.py
- orangewidget/workflow/tests/test_widgetsscheme.py
Orange3 CI tests on macOS frequently stall with something like:
```
test_browse_for_missing (Orange.widgets.data.tests.test_owcsvimport.TestOWCSVFileImport) ... ok
test_browse_for_missing_prefixed (Orange.widgets.data.tests.test_owcsvimport.TestOWCSVFileImport) ... ok
test_browse_prefix (Orange.widgets.data.tests.test_owcsvimport.TestOWCSVFileImport) ... ok
test_browse_prefix_parent (Orange.widgets.data.tests.test_owcsvimport.TestOWCSVFileImport) ... ok
test_minimum_size (Orange.widgets.data.tests.test_owcsvimport.TestOWCSVFileImport) ... ok
test_msg_base_class (Orange.widgets.data.tests.test_owcsvimport.TestOWCSVFileImport) ... ok
test_restore (Orange.widgets.data.tests.test_owcsvimport.TestOWCSVFileImport) ... js: Uncaught TypeError: Cannot read property 'id' of undefined
##[error]The …
```
> [FIX] report: Avoid use of processEvents (via evalJS -> wait)

- orangewidget/utils/combobox.py
On (my) mac, the popup covers the border around the line edit, making it i-can't-watch-this ugly.
I think it should be shown a few pixels lower.
How does this look on Linux and Windows?
A perhaps better alternative could be to not show the frame at all.
> Searchable combo filter: Move popup below focus frame

- orangewidget/utils/itemmodels.py
*Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working.*
> Import Sequence from typing, not collections

- orangewidget/utils/listview.py
ListViewSearch does not account for transient scroll bars in line edit layout.
Fixup for gh-85
* Account for transient scroll bars
> listview: Account for transient scroll bars in layout

- orangewidget/gui.py
While a `disables` kwarg exists for checkboxes, disabling checkboxes when extending already written code (e.g., how OWScatterPlot implements OWPlotGUI) is awkward.
This way, it's much easier and simpler to disable a new checkbox (or any control) according to an already existing checkbox.
> Add a `disabledBy` miscellaneous kwarg

- orangewidget/widget.py
I previously submitted #47, which was rejected at a meeting – I assume due to zero != null?
I still think it looks ugly to not have any text next to the empty in/out icon. If not a zero, how about a minus sign?
> widget: Set in/out msg text to - on no input/output

- orangewidget/tests/base.py
Ref: https://github.com/biolab/orange3/issues/4952
* Dispose of widgets created via create_widget helper. This used to be done but then removed in favor of `sip.setdestroyonexit(False)`  (https://github.com/biolab/orange3/issues/1791). However in PyQt5 5.15.0 this does not seem to have any effect.
* Cleanup the dummy signal_manager
> [FIX] Tests: Cleanup created widgets

- orangewidget/widget.py
Reverts biolab/orange-widget-base#98.
This PR crashes the "future compatibility" tests on Orange. We need to either change Orange's tests to accept both, "" and "-", change the tests to accept "-" and merge this PR just before release.
> Revert "widget: Set in/out msg text to - on no input/output"

- orangewidget/utils/tests/test_visual_settings_dlg.py
- orangewidget/utils/visual_settings_dlg.py
On Visual settings dialog Font family does not reset after clicking Reset button.
Besides, saved setting (a font family with '.' prepended) does not apply, when opening a workflow.
Enable reseting combo boxes that use custom models as data source.
> [FIX] FontModel: Fix 'Reset' for model based combos

- orangewidget/workflow/mainwindow.py
Before:
After:
On a sidenote, does anyone actually use the report feature? How is it meant to be used?
> mainwindow: Fixup save report dialog UX

- orangewidget/gui.py
- orangewidget/utils/__init__.py
This PR fixes the failing Orange3 future-compatibility tests.
Spinboxes used to automatically commit on any change in value. This meant it committed its value mid-typing/holding up or down, too.
In testing, spinbox settings were tested by either:
- calling setValue (most often)
- emitting its valueChanged signal (less often)
- calling setValue and then onEnter (least often)
Just calling `setValue` propagates the changes, but does not trigger callbacks/callfronts.
This PR makes setValue work for testing, and deprecates the other two methods of testing. A call to `setValue` will now also trigger callbacks/callfronts.
https://github.com/biolab/orange3/pull/4995 fixes the deprecations, and raises the orange-widget-base version.
> gui: Commit spin value on manual calls to setValue, expose backwards compatibility testing interface

- orangewidget/report/owreport.py
- orangewidget/report/report.py
- orangewidget/report/tests/test_report.py
While HTML display in the report requires WebviewWidget, its snapshot restoring function does not need it. Why not have it available?
This also fixes failing tests without PyQtWebEngine (that is how I started).
Report window is allowed to be shown (with a warning) if pyqtwebengine is missing. It allows the user to use snapshots and to save in the `*.report` format (whatever that is).
> Enable report snapshots without WebviewWidget

- orangewidget/utils/visual_settings_dlg.py
Upon pressing enter in the visual setting dialog, Reset is invoked.
It's more intuitive to type in the title, and press enter to confirm it, rather than to reset it.
Makes the only autoDefault button Close.
> visual_settings_dlg: Default to close button

- orangewidget/tests/test_io.py
- orangewidget/utils/PDFExporter.py
Fixes #111. 
Unsetting clipping before export in one pyqtgraph's object, a backport of pyqtgraph/pyqtgraph#1458
> [FIX] PDF export with pyqtgraph 0.11

- orangewidget/gui.py
Orange3's widget OWSelectRows has a CalendarWidget with an additional editor for hh:mm:ss at the bottom. This widget is generally useful, hence I'd move it to `gui`.
The class in owselectrows set the initial time based on an attribute from the parent. Now, it takes it from an argument, and default to the current time.
> Add CalendarWidgetWithTime (from orange3's owselectrows)

- doc/source/widget.rst
- orangewidget/widget.py
In an effort to make it easier to make a widget, I've reorganized OWBaseWidget a bit, separating it into four sections:
- Widget Metadata
- Widget GUI Layout Settings
- Miscellaneous Options
- Protected Interface
Really, the user should only be looking at the first three sections when creating a widget.
Are these options really used anywhere? Is there any reason to keep them?
```
category = None
version = None
help = None
help_ref = None
url = None
background = None
```
Something I'd love to do is change the default for `want_main_area` to `False`. I assume most people writing a custom widget won't be using the main area. But, this is probably too much of a backward compatibility hassle to do.
Also, is there anything wrong with changing defaults for parameters like `name` from `None` to …
> Reorganize OWBaseWidget

- orangewidget/gui.py
- orangewidget/widget.py
Check this out with biolab/orange3#5013.
Current implementation shows/hides scrollbar each time it's shown, this is distracting.
Also, it'd be nice to have some buttons always visible in widgets (e.g., data projection controls), regardless of scroll position.
Implements a solution similar to the one in biolab/orange-canvas-core#122, making it dynamically update the scroll area's width when scrollbars are disabled/enabled, and when the window is large enough vertically to not show the scrollbar. Therefore, the left side can always be encapsulated in a VerticalScrollArea, making `left_side_scrolling` obsolete.
Also, the buttonsArea was now docked below a scrollable controlsArea. This change deprecates `buttons_area_orientation`.
> Rework left side for better scrollbars and static buttonsArea

- orangewidget/utils/messagewidget.py
Some widgets are too small to display the entire error/warning. If the message has detailed text too, the title isn't shown in the popup/tooltip alongside it.
> messagewidget: For detailed msgs, show full msg on hover/click

- orangewidget/gui.py
- orangewidget/widget.py
Fixes https://github.com/biolab/orange3/issues/5225
You're right @markotoplak, this works well for all widgets :D
Although, some more testing would be nice. Combine this PR with https://github.com/biolab/orange3/pull/5013
> widget: Stretch controlArea to buttonsArea

- orangewidget/gui.py
The transient scrollbar wouldn't disappear, except upon flicking AlwaysOn scrollbar style.
Avoid instantiating a new scrollbar (which is what causes the issue apparently), and use an eventFilter instead of subclass. My guess is, setting a custom scrollBar does not properly call its private `setTransient` method the same way it does ordinarily.
> VerticalScrollArea: Fix transient scrollbar bug

- orangewidget/widget.py
Reverts biolab/orange-widget-base#99 (unreverts #98).
Merge just before release of this package and release of *Orange3*, and then merge biolab/orange3#5002.
> Revert "Revert "widget: Set in/out msg text to - on no input/output""

- orangewidget/utils/webview.py
WebKitView based WebViewWidget fails when getting `js_timout` while WebEngine based WebViewWidget accepts it. Since classes look the same for the user they should support the same parameters.
WebKitView based WebViewWidget
Remove the  `js_timeout` parameter before passing `kwargs` to `WebKitView`
> Handle js_timeout in WebKitView based WebviewWidget

- orangewidget/gui.py
- orangewidget/widget.py
Widgets aren't visually consistent. It'll take a little bit of work in Orange3 and add-ons, but once we're there, everything will be nice. Most of the changes I made in the Orange3 PR simplify the code, I hope that's the case for addons too.
See commit history.
This was written on macOS 10.15.7, working with both QMacStyle and Plastic. Hoping Windows and Linux look ok.
> Widget sizeHint, button/box sizePolicy fixes

- orangewidget/utils/listview.py
https://github.com/biolab/orange3/pull/5252#pullrequestreview-593102438
Also seen in OWBoxPlot.
Set minimum height 100 on listview
> listview: Set minimum size

- orangewidget/utils/signals.py
- orangewidget/widget.py
Provide automated summaries for inputs and outputs. Ref: https://github.com/biolab/orange3/issues/5108.
For proper effect, must be merged with https://github.com/biolab/orange3/pull/5308, but nothing should break if not.
Also: resolves #109.
- Outputs are intercepted on calls to `send` (only new-style signals are supported; this is intentionally as the "old-style" are deprecated for many many years)
- Inputs are intercepted by using the existing decorator that marks inputs
Auto-summary is generated if
- the signal's `auto_summary` flag is not explicitly set to `False`,
- the signal type has a registered summarizing function.
Summarizing functions are registered by adding another type to single-dispatched `orangewidget.utils.signals.summarize`, which must return an instance of …
> Add automated summaries

- orangewidget/gui.py
- orangewidget/settings.py
- orangewidget/tests/base.py
- orangewidget/tests/test_context_handler.py
- orangewidget/tests/test_setting_provider.py
- orangewidget/tests/test_settings.py
- orangewidget/tests/test_settings_handler.py
- orangewidget/tests/utils.py
- orangewidget/utils/filedialogs.py
- orangewidget/widget.py
Implements #20.
PR defines a set of allowed types and requires proper annotations when the type is not deducible from the default.
- The list of allowed types includes `IntEnum` and `NamedTuple`, as well as `set`, `tuple` and `bytes` which can easily be converted before encoding to json.
- Context handlers can add other valid types, though they are expected to encode them, like, for instance, `Variable` which is already encoded into tuple.
- If setting's default is an empty `list`, `set`, `dict` or `tuple`, it must be annotated, e.g. as `List[int]`. All these must be homogenous; named `tuple` is an exception.
- Type checking is deep, e.g. a `List` must contain only elements of allowed types. Dict's keys must be `int`, `float`, `str` or `bool`, to match those allowed in json.
Also:
- …
> Typed and json-like-storable Settings

- orangewidget/settings.py
- orangewidget/tests/test_settings_handler.py
Should fix https://github.com/biolab/orange3/issues/5339.
`Provider.initialize` did not unpack stored settings.
> Provider.initialize: unpack settings instead of just copying

- orangewidget/settings.py
- orangewidget/tests/test_settings_handler.py
Reverts biolab/orange-widget-base#141
> Revert "Provider.initialize: unpack settings instead of just copying"

- orangewidget/gui.py
- orangewidget/widget.py
`addSpace` deprecation warnings are thrown from within `widget.py`
- better deprecates addSpace (also catching =None)
- fixes miscellania docstring
- resolves deprecation
> Better deprecate addSpace

- orangewidget/tests/test_widget.py
- orangewidget/widget.py
If want_basic_layout = False then `sizeHint` raises an exception
```
File "/Users/aleserjavec/workspace/orange-widget-base/orangewidget/widget.py", line 990, in sizeHint
csh = self.controlArea.sizeHint()
AttributeError: 'NoneType' object has no attribute 'sizeHint'
```
* Avoid sizeHint overload if want_basic_layout is False
> [FIX] widget: Avoid sizeHint if want_basic_layout is False

- orangewidget/gui.py
Fixes #134 
It still listens for drag events on the text, but I've made the value increase exponentially (not linearly), so it should be easy enough to select the text. Is this okay? If not, I'll remove the listener from the textbox. @borondics @janezd
> gui: Make draggable spinbox text selectable, fix disabled behavior

- orangewidget/settings.py
At some point, we (probably: I) decided that `_apply_setting`, which copies a setting to a widget should update mutable settings instead of assigning new values. This decision was correct because it keeps any references to these objects valid.
Updates of UX controls are triggered by assigning values to widget's attributes; e.g. if `self.allow_metas` is tied to some checkbox, setting `self.allow_metas = True` will update the state of that checkbox.
A problem with the above decision is thus that updating in place does not trigger an update of the UX control. This is a problem particularly in selections in list views, which store the selection in a list of variables. When opening the context, the selection is properly updated but not reflected in the list view.
Until now, the few widgets …
> _apply_setting: trigger control update

- doc/source/orange-demo/orangedemo/OWLearningCurveA.py
- doc/source/orange-demo/orangedemo/OWLearningCurveB.py
- doc/source/orange-demo/orangedemo/OWLearningCurveC.py
- doc/source/tutorial-channels.rst
- doc/source/widget.rst
- orangewidget/tests/base.py
- orangewidget/utils/signals.py
- orangewidget/widget.py
- orangewidget/workflow/tests/test_widgetsscheme.py
- orangewidget/workflow/utils.py
- orangewidget/workflow/widgetsscheme.py
- setup.py
Ref: https://github.com/biolab/orange-canvas-core/issues/86
Requires https://github.com/biolab/orange-canvas-core/pull/161 to be merged and released.
Add a new `MultiInput` description to managed explicitly ordered sequence of (multiple) inputs.
i.e. 
```python
...
class Inputs:
foo = MultiInput(...)
...
@Inputs.foo
def set_foo(self, index, foo):
self.foo[index] = foo
@Inputs.foo.insert
def insert_foo(self, index, foo):
self.foo.insert(index, foo)
@Inputs.foo.remove
def remove_foo(self.index)
self.foo.pop(index)
```
> [ENH] signals: Explicit insert/remove handlers

- orangewidget/gui.py
- orangewidget/utils/itemdelegates.py
Ref https://github.com/biolab/orange3/issues/5553
Fix ColoredBarItemDelegate's text color for inactive window
> [FIX] gui: ColoredBarItemDelegate text color for inactive window

- orangewidget/utils/webview.py
On slow machines (sometimes on any computer) connection to receive objects can take longer than default timeout 5s. 
Reproduce: Open any widget which uses highchart (line chart in timeseries).
Increasing timeout for connection to receive objects
> QWebEngineView: increase send_object timeout

- orangewidget/utils/listview.py
- orangewidget/utils/tests/test_listview.py
When using VariableListModel (which updates model with inserting, removing and do not change the root) filtering is not applied on new values. 
Reason:
`__filter_rowsAboutToBeRemoved` is not called for newly inserted rows that are filtered out due to the current filter string. This function is not called since the proxy model skip them directly (without inserting). Insertion happens anyway by model assigned to the list view.
Reproduce:
1. Use the file widget in Orange and select Iris
2. Connect discretize widget and filter values in list view
3. Change the dataset to housing in the file widget
4. Observe that filtering is not applied to new values in the list
Filter values that are inserted by the model are set to the list view.
@ales-erjavec if you have any better solution you are …
> [FIX] ListViewSearch: handle filtering of newly inserted value

- orangewidget/widget.py
- Warning about deriving from non-open widget classes does not set the `stacklevel`.
- I always have to search what do I have to change to fix this.
Add stacklevel and some instructions to the warning.
> Warning about closed class: add stacklevel and instruction

- orangewidget/tests/test_widget.py
- orangewidget/utils/signals.py
If an input signal handler is overridden in derived class, auto summary is called in each handler.
Before calling the summary, check that the method is not overridden.
> Don't call auto summary on derived inputs

- .github/workflows/run-docs-build.yml
- .github/workflows/run-tests-workflow.yml
ubuntu-16.04 GH Actions worker was deprecated and removed - https://github.com/actions/virtual-environments/issues/3287
Replace ubuntu-16.04 worker
> [CI] gh-actions: Replace ubuntu-16.04 worker

- .readthedocs.yml
- doc/requirements-rtd.txt
Documentation faild fails sicne docutils 0.18 is not compatible with shphinx
The problem is solved in the newest sphinx (they pin docutils). -> pinning sphinx to newest versions
After pinning the other error appeared. Since using the requirements file it installs first (separately) requirements and then orange-widget-base in a separate step. Since readthedocs use eager upgrade strategy it upgrades docuitls to newest even it is pinned by spihnx when installing orange-widget-base.
I removed requirements-rtd.txt and put rtd requirements in `EXTRAS_REQUIRE` when installing with .[doc] installation happens in the same step and the problem with forcing docutils to upgrade is solved.
> Fix read-the-docs builds

- orangewidget/workflow/discovery.py
Related to: https://github.com/biolab/orange3/issues/5370
Preserve category if a widget defines it. Remove some weird leftover logic from Orange 2.7
Previously `OWBaseWidget.category` would only be used when the widget was registered explicitly via setup tools entry point like:
```
entry_points = {"orange.widgets": ("SomeWidget = some.package.widgets.OWSomeWidget")}
```
as apposed to via a containing 'category package'. Now `category` should be respected even if/when discovered via a category package.
> discovery: Preserve `category` if a widget defines it

- orangewidget/gui.py
- Labels are currently centered; this makes the right margin rugged (i.e. not aligned with other widgets in control area or the box). These labels are numbers so aligning to the right would make more sense.
- Most function in gui expose the box in widget the control is put. `hSlider` does not. It also does not expose the label, which prevents the caller from, for instance, setting its width.
> gui.hSlider: Right-align the label, expose box and label

- orangewidget/widget.py
- orangewidget/workflow/mainwindow.py
Tests print lots of warnings like:
DeprecationWarning: an integer is required (got type KeyboardModifiers).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python
> Remove deprecation warnings due to QKeyboardSequence

- orangewidget/gui.py
Fixes https://github.com/biolab/orange3/issues/5730.
`gui.hSlider` created a box that was not added to layout (only the slider itself was later explicitly added to form layout). This box was invisible but apparently stole clicks from the slider. (The problem appeared because there we multiple sliders and the boxes of those below were put over the top slider.)
Create the box only when necessary, plus in a case where it is harmless and needed for backward compatibility.
> gui.hSlider: Don't create unnecessary hBox

- orangewidget/utils/webview.py
```
File ".../orange-widget-base/orangewidget/utils/webview.py", line 243, in __init__
settings.setObjectCacheCapacities(4e6, 4e6, 4e6)
TypeError: setObjectCacheCapacities(int, int, int): argument 1 has unexpected type 'float'
```
At some point the above function stopped accepting floats for its int parameters.
> [FIX] webview: Fix argument type

- orangewidget/tests/test_widget.py
- orangewidget/widget.py
Fixes https://github.com/biolab/orange3/issues/5870
Account for control area visibility in splitter width hint
> [FIX] widget: Account for control area visibility in splitter width hint

- orangewidget/utils/itemdelegates.py
Ref: https://github.com/biolab/orange3/issues/5915
Improves responsiveness, when displaying long text although still not great.
Remove a temporary assignment that prevented elided text from being cached.
> [FIX] itemdelegate: Fix text cache when elision takes place

- .github/workflows/run-tests-workflow.yml
Tests fail to import and segfault on windows when installing PyQt6==6.2.* and PyQt6-Qt6==6.3.*
> [CI] Specify full PyQt6 Qt lib version

- orangewidget/report/report.py
Since from Python 3.6, all dictionaries are ordered and in practice (in widgets) regular dicts are passed to report methods I am changing the OrderedDict parameter type to the regular dictionary. It will solve the ugly highlighting of report code by PyCharm in many widgets.
> Report: change OrderedDict parameters types to dict

- orangewidget/tests/test_widget.py
- orangewidget/utils/messagewidget.py
- orangewidget/utils/signals.py
- orangewidget/widget.py
Provide previewers for input and output signals.
- Refactor `MessageWidget` into a widget with a single message and a derived widget that composes a message from multiple messages (the current functionality)
- Derive a new class for messages showing input and output
- Add previewers for signals: `PartialSummary` has a new attribute for a callback that provides a preview widget
> Transient preview of input and output signals

- orangewidget/gui.py
`spinBox` crashes when not given a widget to be inserted into. This prevents its use in, say, grid layout.
Don't assign attributes to `None`.
> gui.spinBox: Fix crash when no parent

- orangewidget/gui.py
`gui.combobox` doesn't support setting tooltips, which is annoying.
Add argument `tooltips`.
> gui.combobox: Add tooltips argument

- doc/source/conf.py
Sphinx fails because language is not set (this is a warning, but `-W` elevates it into an error).
Set language to `"en"`.
> Sphinx: Set language

- .github/workflows/run-tests-workflow.yml
Linux gh actions runners started failing with 'qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.'
Add libxcb-shape to installed linux system packages
Also update deprecated macos-10.15 runners
> [MNT][CI] Add libxcb-shape to linux system packages

- orangewidget/widget.py
Fixes: https://github.com/biolab/orange3/issues/6040
From Qt docs: The use of this flag is not recommended in multi-monitor
environments. This is because the system will enforce that the window
maintains its native size when moving it across screens. This is
particularly undesirable when using monitors with different
resolutions.
Remove Qt.MSWindowsFixedSizeDialogHint flag
> [FIX] widget: Remove Qt.MSWindowsFixedSizeDialogHint flag

- doc/requirements-rtd.txt
- orangewidget/tests/base.py
- orangewidget/tests/test_gui.py
- orangewidget/utils/tests/test_signals.py
- orangewidget/utils/tests/test_widgetpreview.py
- orangewidget/workflow/tests/test_widgetsscheme.py
pyqtgraph installs a `sys.excepthook` to suppress errors in slots/event handlers. This can mask errors in tests which happen in Qt invoked slots/event handlers, ...
Reset the `sys.excepthook` to let the test abort on error. 
Undo pyqtgraph's excepthook override, let the program abort on unhandled exception in a slot, event handler, ...
> GuiTest: Undo pyqtgraph's excepthook override

- orangewidget/utils/itemmodels.py
- orangewidget/utils/tests/test_itemmodels.py
For `PyListModel`, separators work properly only if inserted/set via `__setitem__`, e.g. `model[len(self.x_model):] = [PyListModel.Separator]`. Meanwhile, `model.append(PyListModel.Separator)` inserts an empty item (which can be even selected).
The problem occurs because only `__setitem__` properly sets the corresponding flag entry. Instead of adding similar code to all other places that can add a separator, this PR fixes methods `setData` and `flags` to return the proper data for separators.
For backward compatibility (with what?) setting any other flag overrides the flag for separator.
> PyListModel: Fix Separator's flags

- orangewidget/gui.py
Consider the following code:
```python
cb = gui.checkBox(
None, self, "label_only_subset", "Show labels only for subset",
disabled=True,
callback=self._update_labels, stateWhenDisabled=False)
```
Suppose that `label_only_subset` is initially `True`. This will add the check box, connect the corresponding signals and, at the very end, call the checkbox's `setDisabled(True)`. This will result in a call of method `_updateChecked`, which will  call `setCheckState(False)`. Because the checkbox was initially `True`, this therefore triggers the specified callback, that is, the widget's method `_update_labels`. This fails because the widget is not fully initialized yet.
The solution proposed in this PR, blocking signals, will block all signals caused by changing the state of the checkbox. The …
> [FIX] Check box with disabled state: Block signals

- orangewidget/utils/itemmodels.py
- orangewidget/utils/tests/test_itemmodels.py
AbstractSortTableModel does double remap in `_sortColumnData` in the fallback path when `sortColumnData` is not reimplemented.
Do not remap indices in fallback path. They are already mapped by `data()`
> itemmodels: Do not remap indices in fallback path

- orangewidget/gui.py
On Python 3.10 and higher 'dragging' on a SpinBox raises an type error
```
File "/Users/aleserjavec/workspace/orange-widget-base/orangewidget/gui.py", line 631, in eventFilter
self.setValue(self.preDragValue + valueOffset)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
```
E.g. in Orange's kNN widget click the 'Number of neighbors' spin box and drag up/down.
> [FIX] SpinBox: Fix an type error due to implicit float -> int conversion

- .github/workflows/run-docs-build.yml
- .github/workflows/run-tests-workflow.yml
Add Python 3.11 to test matrices
* Add Python 3.11 to test matrices
* Drop Python 3.6 from test matrices
* Update used gh actions to avoid runner deprecation warnings
> [CI] Add Python 3.11 to test matrices

- orangewidget/gui.py
- orangewidget/report/report.py
- orangewidget/utils/filedialogs.py
- orangewidget/utils/messagewidget.py
- orangewidget/workflow/mainwindow.py
- setup.py
Some strings are composed in a way that may pose problems for translation:
- strings formed using `format` with multiple (unlabeled) `{}`
- or with a single `{}` because translation may not require (or easily accommodate) the value inserted by `{}`.
- strings formed by concatenation of partial messages
- plurals were formed by adding an -s.
- Replace problematic `str.format`'s with f-strings
- Add a better function for plural forms, and use it
> Use f-strings for plural forms and other interpolation

- orangewidget/utils/listview.py
- orangewidget/utils/tests/test_listview.py
`ListViewFilter` has a setter method `set_source_model`. A getter `source_model` would be convenient, so we wouldn't have to call `model().sourceModel()`.
Here it is.
> ListViewFilter: Add methods source_model

- orangewidget/gui.py
- orangewidget/tests/test_gui.py
Ref: #226.
#210 allows for changing push buttons, but with @BlazZupan and @markotoplak we couldn't agree on clear, yet aesthetically pleasing way to indicate a dirty state. I initially didn't like their alternative idea of indicating dirty/clean state by enabling/disabling the button, but now that I tried it I find it simple and clean.
I think we should keep the code from #210 (just modified to a more general form) for potential use elsewhere.
> auto_commit: Disable button on clean, enable on dirty

- orangewidget/tests/test_widget.py
- orangewidget/utils/signals.py
- orangewidget/utils/tests/test_widgetpreview.py
- orangewidget/widget.py
This is needed for https://github.com/biolab/orange-canvas-core/pull/257 to have an effect, but can be merged independently.
Most signals do not have ids, but if they are defined in a class, the name of the attribute that they are assigned to can be used as default id.
This PR also checks that id's and names are unique (which should had already been an error), and warn if the same name and id do not refer to different signals (which is required for backward compatibility of https://github.com/biolab/orange-canvas-core/pull/257).
> Use signal's class-attribute name as default id

- orangewidget/report/report.py
- orangewidget/report/tests/test_report.py
Fixes https://github.com/biolab/orange3/issues/6209.
- Removes border around selected cells.
- For selected cells, it ignores colors by model and uses highlight colors from palette.
- Uses delegate's `displayText` (if it exists) to format the value
- Puts decoration in the same line (`display: inline`) and vertically centers it.
- Adds an argument `indicate_selection` that can be set to `False` in widgets that do not want to show selection in reports.
> Report: improve report_table

- orangewidget/tests/test_widget.py
- orangewidget/widget.py
When translating widget, e.g. to Slovenian, one can translate keywords (literally, or replace the by other words), but can't increase their number. This would be desirable because some languages may have more applicable keywords, and also because we often want to keep the original, English keywords.
Keywords can now also be given as a string (separated with commas or just spaces). Meta class converts them to strings.
This assumes that keywords are always single words. I believe this to be harmless; if somebody uses a keyword "classification tree", this will simply match both, "classification" and "tree".
> BaseWidget: Allow keywords as strings

- orangewidget/tests/test_widget.py
- orangewidget/widget.py
On platforms without a native menu bar pressing the hamburger menu button causes an error when using PyQt6.
```
-------------------------- AttributeError Exception ---------------------------
File "/home/ales/devel/orange-widget-base/orangewidget/widget.py", line 1313, in __showStatusBarMenu
screen_rect = QApplication.desktop().availableGeometry(b)
^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QApplication' has no attribute 'desktop'
-------------------------------------------------------------------------------
```
Replace use of `QApplication.desktop`. Add a test that covers the code in question.
> [FIX] widget: Fix PyQt6 compatibility in __showStatusBarMenu

- orangewidget/utils/itemmodels.py
- orangewidget/utils/tests/test_itemmodels.py
`AbstractSortTableModel._argsortData` does not perform a stable descending sort.
It essentially does `reversed(argsort(data))` which is not stable. 
* Ensure stable descending sort (argsort on reversed data then reverse and invert the resulting indices).
> [FIX] itemmodels: Ensure stable descending sort

- orangewidget/tests/base.py
- orangewidget/tests/test_test_base.py
We do not run tests on Slovenian version of Orange because they fail on language-dependent strings. Some tests can be made language independent, while some not (at least not easily).
- Add decorator `GuiTest.skipNonEnglish`, which skips a test if `GuiTest.LANGUAGE` is not "English".
- Also add decorator `GuitTest.runForLanguage(lang)` which allows specifying a language on which the test should be run.
The former is of course a shortcut for the latter.
> TestGui: Add decorators for enabling tests depending upon language

- orangewidget/gui.py
Different-colored indicators may be difficult to distinguish. 
This PR adds another visual cue besides color: indicator can be hollow or filled.
Backward compatibility with existing widget should work, I guess. IMHO, indicators are used only the Datasets widget, which is adapted accordingly, so this is not much of concern.
> IndicatorItemDelegate: Show hollow indicators

- orangewidget/utils/concurrent.py
Deprecation warnings when running with PyQt6 e.g.
```
rangewidget/utils/tests/test_concurrent.py::TestFutureWatcher::test_watcher
/home/ales/devel/orange-widget-base/orangewidget/utils/concurrent.py:202: DeprecationWarning: QEvent constructor is deprecated
selfref, QEvent(FutureWatcher.__FutureDone))
```
Change type of event type constants.
> [FIX] Fix PyQt6 warnings

- orangewidget/io.py
- orangewidget/tests/test_io.py
Images were stored in logical resolution instead of physical.
- For pyqtgraph objects, reimplement `ImageExporter` to observe the resolution.
- For other graphics, do the same :)
- ~~Do not use QGraphicsScene's rect for resolution; this doesn't work for widgets with mapping, e.g. `OWSOM`~~.
- Widgets that transformed the scene (e.g. OWSOM, which used grid coordinates in scene) had to export the view, not the scene. With this PR, the widget can export a scene and it will be rendered by the view, which will keep transformations, but export entire scene, not just the view.
~~**To discuss**:~~
~~- Widgets that transform scenes, such as `OWSOM` must export view, not scene because scene's render ignores transformations. To export scenes (which would also allow adjusting to any png resolution, …
> Fix resolution when saving images and copying to clipboard on high-dpi displays

- orangewidget/io.py
- orangewidget/report/report.py
- orangewidget/tests/test_io.py
#208 introduced some issues.
- Fixes https://github.com/biolab/orange3/issues/6391 by casting dimensions that are passed to `QImage` to ints. (`QPaintDevice` has methods `devicePixelRatio` and `devicePixelRatioF`, where the latter is defined as `qreal devicePixelRatioF()  const { return devicePixelRatio(); }`. Thanks, Qt, for misleading.)
- Fixes https://github.com/biolab/orange3/issues/6392 by handling instances of `QGraphicsWidget` and `QGraphicsView` instead of just pyqtgraph's `GraphicsWidget` and `GraphicsView`.
- Fixes rendering of `QWidget`s; `render` was called with `QPointF` instead of with `QPoint`. This disabled saving of content of Image Viewer (which doesn't work well anyway because it clips the content).
> Fix image export

- orangewidget/utils/messages.py
- orangewidget/utils/tests/test_messages.py
`Error.clear()` clears messages up and down in the hierarchy of widgets, which makes it safe only for flat classes. Base classes mustn't use it to avoid clearing subclass messages, and derived classes shouldn't use it even if base classes have no messages because they may be added in the future. If one wants to be cautious, he must clear each message separately, which is annoying if there are too many.
`MessageGroup.clear` now accepts an argument `owner: Type[OWBaseWidget]`, and only deletes messages defined within the given class. E.g.`self.Error.clear(owner=OWNxFile)` would clear messages defined in `OWNxFile` but not those from its base classes or subclasses.
@ales-erjavec, searching for the class that defines a message group must be done during binding, and requires searching for …
> MessageGroup.clear: Add argument owner

- .github/workflows/run-tests-workflow.yml
PyQt6 6.5 tests fail on ubuntu-20.04 due to
https://www.riverbankcomputing.com/pipermail/pyqt/2023-June/045313.html
Use ubuntu-22.04 image
> [MNT] ci: Update ubuntu image for PyQt6 6.5 tests

- orangewidget/utils/filedialogs.py
- orangewidget/utils/tests/test_filedialogs.py
Fixes https://github.com/biolab/orange3/issues/6453.
In file dialog combos, keep as much directories as necessary to disambiguate between the paths.
The code also allows for keeping more, for instance always keeping the last directory. In case we decide we prefer it.
> File dialog: Add as much path as necessary to make names unambiguous

- orangewidget/io.py
Fixes biolab/orange3#6543
Display size is set after painting. This keeps proper display size (intention of #246 that solved bug #240) and fixes the obnoxious axis problems.
> [FIX] Fix axes in PNG export

- .readthedocs.yml
RTD docs build [fails](https://readthedocs.org/projects/orange-widget-base/builds/21933713/) due to dropped [system_packages](https://blog.readthedocs.com/drop-support-system-packages/) key 
Remove `system_packages` key
> [MNT] readthedocs: Remove no longer supported 'system_packages'

- orangewidget/utils/itemmodels.py
Using PyQt6 6.5.3 (still unreleased on PyPi but available at https://www.riverbankcomputing.com/pypi/simple/)
```
File "/home/ales/devel/orange-widget-base/orangewidget/utils/tests/test_itemmodels.py", line 164, in test_set_item_signals
self.model[2:4] = p(6, 7, 8, 9, 10) + [[11, 2]]
~~~~~~~~~~^^^^^
File "/home/ales/devel/orange-widget-base/orangewidget/utils/itemmodels.py", line 437, in __setitem__
self.rowsAboutToBeInserted.emit(parent, stop, newstop - 1)
AttributeError: 'PyTableModel' does not have a signal with the signature rowsAboutToBeInserted(QModelIndex, int, int)
```
rowsAboutToBeRemoved/Inserted, ... are private signals of QAbstractItemModel and should not be emitted directly. Use beginInsert/RemoveRows and endInsert/RemoveRows instead. …
> [FIX] itemmodels: Remove use of private signals from PyTableModel

- .readthedocs.yml
RTD docs build [fails](https://readthedocs.org/projects/orange-widget-base/builds/22268358/) due to missing [build.os key](https://blog.readthedocs.com/use-build-os-config/)
> [MNT] readthedocs: Add build.os key

- doc/source/conf.py
- orangewidget/gui.py
- orangewidget/report/owreport.py
- orangewidget/utils/__init__.py
- orangewidget/utils/messages.py
- orangewidget/widget.py
- orangewidget/workflow/config.py
- orangewidget/workflow/discovery.py
- orangewidget/workflow/errorreporting.py
- setup.py
[pkg_resources](https://setuptools.pypa.io/en/latest/pkg_resources.html) is deprecated.
Requires https://github.com/biolab/orange-canvas-core/pull/289 
Remove/replace use of pkg_resources with importlib.metadata, importlib.resources, pkgutil and packaging.
> [ENH] Remove use of pkg_resources

- setup.py
`imp` module was deprecated and removed in Python 3.12. This means that installing from a sdist package fails on Python 3.12+.
Replace use of imp module
> [FIX] setup.py: Replace use of imp module

- orangewidget/gui.py
Fixes https://github.com/biolab/orange3/issues/6715
gui.spin creates an extra widget box on the parent which interferes with mouse interaction
I.e:
Note that the layout depends on the style, should be tested on Windows. 
Remove extraneous created widget box
> [FIX] gui.spinBox: Remove extraneous created widget box

- .github/workflows/run-docs-build.yml
- .github/workflows/run-tests-workflow.yml
Various actions raise warnings
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`
Update actions
> [MNT] ci: Update various action versions

- orangewidget/utils/listview.py
- orangewidget/utils/tests/test_listview.py
Fixes https://github.com/biolab/orange3/issues/6768
The default selection corresponds to `QSortFilterProxyModel`. 
Apply selection mapped to a source model.
> ListViewFilter: Retain selection when filtering

- orangewidget/widget.py
Fixes [#6799](https://github.com/biolab/orange3/issues/6799)
Help button was not present in all widgets, only in those with resizing disabled (e.g. CSV File Import, Data Info, Constant, kNN, ...), where the window type was Qt.Dialog instead of Qt.Window. Now it should be gone everywhere as we have our own.
> Remove window help button

- orangewidget/utils/messages.py
- orangewidget/utils/tests/test_messages.py
Fixes #272. (@hoywu, thanks for catching this!)
Condition `group in widget_class.__dict__.values()` expected that all class members have an `__eq__` operator in which "other" can be a class (message group).
If somebody adds a numpy array or pandas dataframe as class attribute (e.g. `pd`), it will compare `group == pd`, which fails with `The truth value of a DataFrame is ambiguous.`.
We know the name of the attribute (the class name) and can check that the instance is the same (not just equal).
> WidgetMessagesMixin: Fix message binding to not expect class attributes to have `__eq__`

- .github/workflows/run-tests-workflow.yml
macos-11 github actions runners are deprecated. Replace them.
Replace deprecated macos-11 GH runners
> [MNT] ci: Replace deprecated macos-11 GH runners

- .github/workflows/run-docs-build.yml
- .github/workflows/run-tests-workflow.yml
- .readthedocs.yml
- MANIFEST.in
- doc/requirements-rtd.txt
- doc/source/conf.py
- i18n/si/msgs.jaml
- i18n/si/trubar-config.yaml
- i18n/trans.sh
- i18n/trubar-config.yaml
- setup.py
> Multilingual configuration

- orangewidget/report/owreport.py
- orangewidget/report/tests/test_report.py
In Qt6, `QPrinter` no longer contains an enum with page sizes, e.g. `QPrinter.A4`. I haven't found a notice that enum is obsolete and removed, but I found [this](https://doc.qt.io/qt-5/qprinter-obsolete.html#setPaperSize).
To reproduce, on macOS:
- Report something
- Click Print
- Choose PDF -> Save as PDF ...
- Enter file name, click Save
Crashes with 
```
File "/Applications/Orange.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/orangewidget/report/owreport.py", line 350, in save_report
printer.setPageSize(QPrinter.A4)
^^^^^^^^^^^
AttributeError: type object 'QPrinter' has no attribute 'A4'
```
Use `QPageSize`.
> Report: Fix saving to PDF
