- orangewidget/workflow/widgetsscheme.py
> [FIX] Fix lost signals due to explicit event loop reentry

- orangewidget/workflow/errorreporting.py
https://github.com/biolab/orange3/issues/3953
Report application version and not this project's
> errorreporting: Report application version and not this project's

- orangewidget/tests/base.py
Implements https://github.com/biolab/orange3/issues/3977
> [ENH] WidgetTest: Check widget's messages inheritance

- orangewidget/gui.py
- orangewidget/tests/test_gui.py
callback_finished is called when the slider value stopped changing for at least 500 ms or when the slider is released.
A supporting class DelayedNotification was added to gui.py.
I opted to solve this problems with timing proxies on existing signals, because an alternative that would use sliderReleased signal would not solve similar problems for the keyboard and mouse wheel (+ it would require reimplementing lots of events).
This was done for biolab/orange3#3962
> gui.hSlider with callback_finished

- orangewidget/tests/base.py
- orangewidget/tests/test_widget.py
- orangewidget/utils/signals.py
- orangewidget/widget.py
- orangewidget/workflow/tests/test_widgetsscheme.py
- orangewidget/workflow/widgetsscheme.py
- setup.py
Add support for per-channel output invalidation.
Requires https://github.com/biolab/orange-canvas-core/pull/34
Add support for channel invalidation
> [ENH] Add support for output channel invalidation

- orangewidget/workflow/widgetsscheme.py
Referencs: https://github.com/biolab/orange3/issues/4211
Reorder signal delivery to match the order of links in the model
> widgetsscheme: Reorder pending signals to match

- orangewidget/widget.py
Windows users see no indicator in splitter. On other systems, the indicator does not suggest that clicking it will show/hide the control area.
Make the splitter wider and add an arrow that changes directions on show/hide.
> Add hide/show indicator in splitter between control and main area

- orangewidget/settings.py
- orangewidget/tests/base.py
- orangewidget/tests/test_context_handler.py
- orangewidget/tests/test_settings_handler.py
Implements schema-only context settings (resolves https://github.com/biolab/orange3/issues/4753)
> ContextHandler: Implement schema-only context settings

- .travis.yml
- appveyor.yml
PyQt5 5.15 is out
Add PyQt5 5.15 to CI
> ci: Add PyQt5 5.15 to test matrix

- orangewidget/report/report.py
- orangewidget/report/tests/test_report.py
`report_table` does not format decorators and graphic scenes.
- Implement that decorators are included in the report table
- Implement that graphic scenes are also rendered in the report table
> [ENH] Report add more possibilities to report_table

- orangewidget/report/report.py
Ref https://github.com/biolab/orange3/pull/4812#issuecomment-639710675
Handle high-dpi icon pixmaps
> [ENH] report: Handle high-dpi icon pixmaps

- orangewidget/workflow/errorreporting.py
So that one day we could get rid of letsencrypt certificates.
> Change error report URL

- orangewidget/utils/listview.py
- orangewidget/utils/tests/test_listview.py
Implementing ListViewSearch
Thanks to @ales-erjavec for the implementation, it is his work.
> [ENH] Implement ListViewSearch

- orangewidget/utils/visual_settings_dlg.py
Remove the leading dot from some font names.
> visual_settings_dlg: Add control for font combo boxes

- orangewidget/gui.py
Nobody moves these sliders w/ scroll (intentionally).
Disable wheelEvents on sliders.
> gui: Disable slider wheelEvent

- orangewidget/gui.py
I've always found these fun to use.
> gui: Make spinboxes draggable, make postponing synchronization of value definitive (deprecate callbackOnReturn)

- orangewidget/gui.py
(hopefully the last installment of the spinbox PR saga)
The previous changes discouraged the use of the `valueChanged` signal in testing, and encouraged the use of `setValue`. 
However, I neglected to consider other ways of the spinbox changing its value, as in https://github.com/biolab/orange3-timeseries/pull/141, wherein the spinbox's value is adjusted by a call to `setMaximum` when the spinbox's current value is larger than the argument's. As the value wasn't committed, the widget's Setting's value wasn't adjusted.
A simpler way of enabling valueChanged, and makes less work deprecating things. Both calling `setValue` and emitting `valueChanged` are valid ways of testing, and emitting `valueChanged` outwith user interaction commits and propagates the value.
> gui: Simplify spinbox backwards compat changes

- .travis.yml
- appveyor.yml
Add Python 3.9 to CI jobs matrix
Add Python 3.9 to CI jobs matrix
> CI: Add Python 3.9 to jobs matrix

- orangewidget/widget.py
> widget: handle_data -> set_data

- orangewidget/report/owreport.py
Fixes https://github.com/biolab/orange3/issues/5195
.
> Report window: Set larger initial size

- orangewidget/gui.py
- orangewidget/widget.py
> widget: Adjust margins, make splitter bigger

- orangewidget/workflow/mainwindow.py
Fixes biolab/orange-canvas-core#139
Also, there was a bug where if several workflows were open, only the focused one would be closed, so Orange wouldn't actually quit.
Works after https://github.com/biolab/orange3/pull/5064 is merged and released but doesn't depend on it.
> mainwindow: Restart on reset settings

- orangewidget/utils/cache.py
- orangewidget/utils/itemdelegates.py
- orangewidget/utils/tests/test_itemdelegates.py
- setup.py
Extracted from https://github.com/biolab/orange3/pull/5296
* Add a item delegate(s) with data caching and optimized text painting (using QStaticText)
> [ENH] Caching data delegate

- orangewidget/tests/test_widget.py
- orangewidget/utils/signals.py
Fixes #148. @markotoplak, please confirm.
auto_summarize tried to issue a warning when the signal type was given as fully qualified name (a `str`), but crashed when composing the message.
Instead of catching a `TypeError` (raised by dispatcher when called by a string instead of a type), it now checks whether the type is given as a string and shows a better warning (without crashing).
`auto_summary` is disabled in this case, unless manually enabled in the signal definition. Function `can_summarize` could, in principle, check whether there is a summarizer declared for this name, but it is possible that the summarizer would actually appear later. This would be confusing, so it's better to require explicit `auto_summarize` argument in this (rare) case.
> can_summarize: Fix problems when signal type is given as qualified name

- doc/source/drophandler.rst
- doc/source/index.rst
- orangewidget/workflow/drophandler.py
- orangewidget/workflow/tests/test_drophandler.py
- setup.py
Ref: https://github.com/biolab/orange3/issues/4918
Builds on https://github.com/biolab/orange-canvas-core/pull/143 and defines some helper classes for single/multiple file/url drops.
> [ENH] Add canvas drag/drop utility classes

- orangewidget/gui.py
- orangewidget/tests/test_gui.py
> [FIX] DateTimeEditWCalendarTime: Fix QDateTime module

- orangewidget/gui.py
- orangewidget/io.py
- orangewidget/report/owreport.py
- orangewidget/report/report.py
- orangewidget/report/tests/test_report.py
- orangewidget/tests/utils.py
- orangewidget/utils/PDFExporter.py
- orangewidget/utils/combobox.py
- orangewidget/utils/concurrent.py
- orangewidget/utils/listview.py
- orangewidget/utils/messagewidget.py
- orangewidget/utils/saveplot.py
- orangewidget/utils/tests/test_itemmodels.py
- orangewidget/utils/tests/test_widgetpreview.py
- orangewidget/utils/visual_settings_dlg.py
- orangewidget/utils/webview.py
- orangewidget/utils/widgetpreview.py
- orangewidget/widget.py
- orangewidget/workflow/tests/test_drophandler.py
- setup.py
Remove/replace various obsolete uses of PyQt
Remove/replace various obsolete uses of PyQt
Mostly to deal with removed features and stricter typing with PyQt6.
> Modernize for better forward compatibility with Qt 6

- orangewidget/utils/signals.py
- orangewidget/utils/tests/test_signals.py
Ref https://github.com/biolab/orange3/pull/4860#issuecomment-849490577
There is an error in multi input id tracking.
Fix MultInput auto summary id tracking
> [FIX] signals: Fix error in MultInput auto summary id tracking

- orangewidget/utils/itemmodels.py
- orangewidget/utils/tests/test_itemmodels.py
- Allow lexical sorting
- Expose a method for setting sort indices
> AbstractTableModel: Refactor sort

- orangewidget/gui.py
Click-and-hold on the up/down buttons was not working properly with spinboxes.
Fix click-and-hold issue. Also change the rate at which click+drag changes the value.
> gui: Spinbox click and hold fix

- orangewidget/gui.py
- orangewidget/tests/test_control_getter.py
- orangewidget/tests/test_widget.py
- orangewidget/workflow/widgetsscheme.py
Reverts biolab/orange-widget-base#151
Causes 100% main thread utilization after using Silhouette Plot widget in Orange
> Revert "Implement signals for Setting changes"

- orangewidget/gui.py
- orangewidget/tests/test_gui.py
- orangewidget/utils/tests/test_itemdelegates.py
Fix an error/warning on float to int conversion in gui.py
> [FIX] gui: Fix an implicit float to int conversion error

- orangewidget/workflow/config.py
> [FIX] Allow Orange3 to be missing

- .github/workflows/run-tests-workflow.yml
- orangewidget/gui.py
- orangewidget/tests/base.py
- orangewidget/tests/test_io.py
- orangewidget/tests/utils.py
- orangewidget/utils/__init__.py
- orangewidget/utils/buttons.py
- orangewidget/utils/combobox.py
- orangewidget/utils/filedialogs.py
- orangewidget/utils/itemdelegates.py
- orangewidget/utils/messagewidget.py
- orangewidget/utils/overlay.py
- orangewidget/utils/tests/test_combobox.py
- orangewidget/utils/webview.py
- orangewidget/widget.py
- setup.py
Add support for PyQt6
<s>Needs release of https://github.com/biolab/orange-canvas-core/pull/226 </s>
> [ENH] Add support for PyQt6

- orangewidget/widget.py
Fixes gh-193
Ensure parameters to QWidget.move are ints.
> [FIX] widget: Fix and implicit float to int conversion

- orangewidget/gui.py
- orangewidget/tests/test_gui.py
Fixes: gh-200
Check that bar ratio is valid.
> gui: Fix an NaN/Inf conversion error

- orangewidget/tests/test_io.py
Tests are failing on latest versions.
Change number in test.
> test_io: Change pdf size increase to work on recent pyqtgraph

- orangewidget/utils/listview.py
- orangewidget/utils/tests/test_listview.py
> [FIX] ListViewSearch: Filter on changed data, introduce ListViewFilter

- orangewidget/utils/itemdelegates.py
Fixes https://github.com/biolab/orange3/issues/6175
QPersistentModelIndex destruction is slower in Qt6 when there are many distinct persistent indices registered with the model.
Key the cache with QPMI(parent()), row(), column() to reduce the number of tracked indices.
> [FIX] itemdelegates: Fix performance regression with Qt 6

- orangewidget/tests/base.py
Why do I have to write
```
self.send_signal(self.widget.Inputs.data, iris)
out = self.get_output(self.widget.Outputs.selected_data)
```
even when -- as is often the case -- a widget has a single input and output? Why can't we call just this?
```
self.send_signal(iris)
out = self.get_output()
```
- Change `WidgetTest.send_signal` to accept a single argument (value) when the widget has a single input,
- and change `WidgetTest.get_output` to accept zero arguments when the widget only has a single output.
For both, `self.widget` must be set (as it usually is).
> Simplify calling WidgetTest's send_signal and get_output

- orangewidget/icons/hamburger.svg
- orangewidget/tests/test_widget.py
- orangewidget/utils/__init__.py
- orangewidget/utils/combobox.py
- orangewidget/utils/tests/test_combobox.py
- orangewidget/widget.py
Fixes: https://github.com/biolab/orange3/issues/6187
Requires https://github.com/biolab/orange-canvas-core/pull/248
Add menu with open windows to widgets
> [ENH] Add menu with open windows to widgets

- orangewidget/utils/itemmodels.py
- orangewidget/utils/tests/test_itemmodels.py
> [ENH] Add SeparatorItem and LabelledSeparator

- orangewidget/tests/base.py
`WidgetTest.get_output` returns lazy signals.
We can keep this and let widget tests expect them and call `get_value`; these tests would ensure that widget that are supposed to use lazy signals indeed use them. On the other hand, it's impractical, so I propose this PR.
`get_output` now checks whether the signal is lazy and computes it.
> WidgetTest.get_output: compute lazy signals

- .github/workflows/run-docs-build.yml
- .github/workflows/run-tests-workflow.yml
ubuntu-18.04 actions runners are deprecated
Replace obsolete ubuntu-18.04 runners
> [MNT] CI: Update/replace obsolete ubuntu-18.04 runners

- orangewidget/tests/base.py
See the comment in https://github.com/biolab/orange3/issues/6391. Before merging, we must see that this test works on the headless CI server.
> WidgetTest: Add a test for image export

- .github/workflows/run-tests-workflow.yml
codecov on pypi is no longer available
Use codecov-action
> [MNT] CI: Use codecov-action

- .github/workflows/run-tests-workflow.yml
PyQt6 6.5 LTS has been released.
Add PyQt6 6.5 to test CI matrix.
> [MNT] CI: Add PyQt6 6.5 to test matrix

- pylintrc
pylint 3.0 will remove some deprecated settings.
> pylintrc: Update obsolete settings

- .github/workflows/run-tests-workflow.yml
Test with Python 3.12
Add Python 3.12 to test matrices
Also remove Python 3.7 to ease CI workload
> [MNT] CI: Add Python 3.12 to test matrices

- orangewidget/utils/listview.py
> ListViewFilter: Fix selection

- .github/workflows/run-tests-workflow.yml
- orangewidget/utils/tests/test_combobox.py
Add Python 3.13 and Qt 6.7 to test matrix
> [CI] Add Python 3.13 and Qt 6.7
